<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.5 on linux)" generated="20200331 14:28:06.775" rpa="false">
<suite id="s1" name="Basic tests" source="/home/bogdanterzea/Documents/TestingGo/automated-channel-testing/RobotLibrary/Tests/Basic_tests.robot">
<test id="s1-t1" name="Channel should be launched">
<kw name="Launch the channel">
<arguments>
<arg>${channel_code}</arg>
</arguments>
<msg timestamp="20200331 14:28:06.830" level="FAIL">No keyword with name 'Launch the channel' found.</msg>
<status status="FAIL" starttime="20200331 14:28:06.830" endtime="20200331 14:28:06.830"></status>
</kw>
<status status="FAIL" starttime="20200331 14:28:06.828" endtime="20200331 14:28:06.830" critical="yes">No keyword with name 'Launch the channel' found.</status>
</test>
<test id="s1-t2" name="Check if details screen showed">
<kw name="Send key">
<arguments>
<arg>select</arg>
<arg>4</arg>
</arguments>
<msg timestamp="20200331 14:28:06.831" level="FAIL">No keyword with name 'Send key' found.</msg>
<status status="FAIL" starttime="20200331 14:28:06.831" endtime="20200331 14:28:06.831"></status>
</kw>
<status status="FAIL" starttime="20200331 14:28:06.830" endtime="20200331 14:28:06.831" critical="yes">No keyword with name 'Send key' found.</status>
</test>
<test id="s1-t3" name="Check if playback started">
<kw name="Run Keyword And Ignore Error" library="BuiltIn">
<doc>Runs the given keyword with the given arguments and ignores possible error.</doc>
<arguments>
<arg>Verify is screen loaded</arg>
<arg>${Params5}</arg>
<arg>2</arg>
</arguments>
<assign>
<var>${status}</var>
<var>${value}</var>
</assign>
<kw name="Verify is screen loaded">
<arguments>
<arg>${Params5}</arg>
<arg>2</arg>
</arguments>
<msg timestamp="20200331 14:28:06.833" level="FAIL">No keyword with name 'Verify is screen loaded' found.</msg>
<status status="FAIL" starttime="20200331 14:28:06.833" endtime="20200331 14:28:06.833"></status>
</kw>
<msg timestamp="20200331 14:28:06.833" level="INFO">${status} = FAIL</msg>
<msg timestamp="20200331 14:28:06.833" level="INFO">${value} = No keyword with name 'Verify is screen loaded' found.</msg>
<status status="PASS" starttime="20200331 14:28:06.832" endtime="20200331 14:28:06.833"></status>
</kw>
<kw name="Run Keyword If" library="BuiltIn">
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<arguments>
<arg>"${status}"=="PASS"</arg>
<arg>Do auth</arg>
<arg>ELSE</arg>
<arg>Send key</arg>
<arg>select</arg>
</arguments>
<kw name="Send key">
<arguments>
<arg>select</arg>
</arguments>
<msg timestamp="20200331 14:28:06.835" level="FAIL">No keyword with name 'Send key' found.</msg>
<status status="FAIL" starttime="20200331 14:28:06.835" endtime="20200331 14:28:06.835"></status>
</kw>
<status status="FAIL" starttime="20200331 14:28:06.833" endtime="20200331 14:28:06.835"></status>
</kw>
<status status="FAIL" starttime="20200331 14:28:06.831" endtime="20200331 14:28:06.835" critical="yes">No keyword with name 'Send key' found.</status>
</test>
<doc>Basic smoke tests</doc>
<status status="FAIL" starttime="20200331 14:28:06.776" endtime="20200331 14:28:06.835"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="3">Critical Tests</stat>
<stat pass="0" fail="3">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="3" id="s1" name="Basic tests">Basic tests</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200331 14:28:06.821" level="ERROR">Error in file '/home/bogdanterzea/Documents/TestingGo/automated-channel-testing/RobotLibrary/Tests/Basic_tests.robot': Initializing test library 'RobotLibrary' with arguments [ 192.168.1.102 | 20000 | 2000 | D:/projects/go/webDriver/src/main.exe ] failed: FileNotFoundError: [Errno 2] No such file or directory: 'D:/projects/go/webDriver/src/main.exe': 'D:/projects/go/webDriver/src/main.exe'
Traceback (most recent call last):
  File "/home/bogdanterzea/Documents/TestingGo/automated-channel-testing/RobotLibrary/Library/RobotLibrary.py", line 33, in __init__
    self._process = subprocess.Popen(path)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)</msg>
</errors>
</robot>
